# =========================
# Build stage (Angular)
# =========================
FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# =========================
# Runtime stage (Nginx)
# =========================
FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/encurtador-url-web/browser /usr/share/nginx/html

EXPOSE 80
